service: listory

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.secrets.NODE_ENV}
  region: us-east-1
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
  exclude:
    - client/**
    - .vscode/**
  deploymentBucket:
    name: habl-listory-01
    serverSideEncryption: AES256

functions:
  graphql:
    handler: index.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true
    - http:
        path: playground
        method: any
        cors: true

plugins:
  - serverless-domain-manager
  - serverless-deployment-bucket
  - serverless-offline

custom:
  secrets: ${file(secrets.json)}
  customDomain:
    domainName: ${self:custom.secrets.DOMAIN}
    basePath: ''
    stage: ${self:custom.secrets.NODE_ENV}
    createRoute53Record: true
    # endpointType: 'regional'
    # if the ACM certificate is created in a region except for `'us-east-1'` you need `endpointType: 'regional'`