service: listory

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  region: us-east-1
  environment: 
    NODE_ENV: ${opt:stage}
  deploymentBucket:
    name: habl-listory-01
    serverSideEncryption: AES256

package:
  exclude:
    - client/**
    - '!client/build/**'
    - .vscode/**
    - .env
    - secrets.json
    
functions:
  html:
    handler: index.html
    events:
      - http:
          path: /
          method: get
      - http:
          path: /{proxy+}
          method: get
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

plugins:
  - serverless-domain-manager
  - serverless-deployment-bucket
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
  secrets: ${file(secrets.json)}
  customDomain:
    domainName: ${self:custom.secrets.DOMAIN}
    basePath: ''
    stage: ${opt:stage}
    createRoute53Record: true